import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    {
      dirName: 'skill',
      type: 'autogenerated',
    },
  ],
  work: [
    {
      dirName: 'work',
      type: 'autogenerated',
    },
  ],
  tools: [
    {
      dirName: 'tools',
      type: 'autogenerated',
    },
  ],
}

module.exports = sidebars
